/**
 * Creative titles for AI Daily Mix playlists.
 * Used when a mix has many artists (3+) so we avoid repetitive "Artist & Friends".
 * Scales for many artists and users — each mix gets a distinct, creative name.
 */

const TITLES = [
  "Today's Picks",
  "Fresh Finds",
  "Curated for You",
  "Discovery Mix",
  "Your Sound Today",
  "Mixed Vibes",
  "New & Noteworthy",
  "Just for You",
  "Listen Next",
  "Sound Escape",
  "Daily Discovery",
  "Personal Blend",
  "Fresh Cuts",
  "Your Rotation",
  "Handpicked",
  "The Blend",
  "Fresh Rotation",
  "Today's Blend",
  "Sonic Journey",
  "Picked for You",
  "Discovery Hour",
  "Your Vibe",
  "Fresh Sounds",
  "The Daily Cut",
  "Listen List",
  "Sound Picks",
  "Curated Mix",
  "Today's Sound",
  "Your Discovery",
  "Fresh Picks",
  "Backstage Pass",
  "The Playlist",
  "Sound Check",
  "Encore",
  "Spotlight Mix",
  "Hidden Gems",
  "Rising Stars",
  "Deep Cuts",
  "Crowd Favorites",
  "Late Night Sessions",
  "Morning Groove",
  "After Hours",
  "Peak Time",
  "Golden Hour",
  "Midnight Run",
  "Sunrise Sounds",
  "Twilight Mix",
  "Golden Era",
  "New Wave",
  "Next Gen",
  "Future Sounds",
  "Throwback Hour",
  "Now Playing",
  "On Repeat",
  "Never Skip",
  "Hit Parade",
  "Chart Toppers",
  "Under the Radar",
  "Off the Grid",
  "Wild Cards",
  "Lucky Dip",
  "Surprise Me",
  "Random Acts",
  "Serendipity",
  "Happy Accidents",
  "Ear Candy",
  "Soul Food",
  "Mood Board",
  "Vibe Check",
  "Frequency",
  "Wavelength",
  "Signal",
  "Transmission",
  "Broadcast",
  "Airwaves",
  "Static",
  "Reception",
  "Tuned In",
  "Locked In",
  "In the Zone",
  "Flow State",
  "Headspace",
  "Escape Plan",
  "Time Out",
  "Breathing Room",
  "Clear Skies",
  "Open Road",
  "Wide Open",
  "Unfiltered",
  "Raw Cuts",
  "Pure Sound",
  "Stripped Down",
  "Full Spectrum",
  "All In",
  "The Whole Thing",
  "Everything Bagel",
  "Kitchen Sink",
  "Best Of",
  "Greatest Hits",
  "Essentials",
  "Must Haves",
  "Can't Miss",
  "Don't Sleep",
  "Wide Awake",
  "Eyes Open",
  "Ears Open",
  "Taste Makers",
  "Trendsetters",
  "Pioneers",
  "Trailblazers",
  "Originals",
  "One of One",
  "Unique",
  "Rare Finds",
  "Limited Edition",
  "Exclusive",
  "VIP Mix",
  "Members Only",
  "Inner Circle",
  "Inner Sanctum",
  "Secret Sauce",
  "Special Sauce",
  "Magic Hour",
  "Lucky Charm",
  "Good Fortune",
  "Blessed",
  "Chosen",
  "Selected",
  "Elected",
  "Crowned",
  "Champion",
  "Winner's Circle",
  "Top Tier",
  "Elite",
  "Premium",
  "Platinum",
  "Gold Standard",
  "Blue Ribbon",
  "Seal of Approval",
  "Certified",
  "Verified",
  "Authentic",
  "Genuine",
  "Real Deal",
  "No Skip",
  "Zero Skip",
  "Full Play",
  "Straight Through",
  "Front to Back",
  "Start to Finish",
  "End to End",
];

export const CREATIVE_MIX_TITLES: string[] = TITLES;

const L = CREATIVE_MIX_TITLES.length;

/**
 * Get a creative title by index (0 to L-1). Used for per-user rotation so
 * the same user doesn't see a repeated title until all have been shown.
 */
export function getCreativeMixTitleByIndex(index: number): string {
  const i = ((index % L) + L) % L;
  return CREATIVE_MIX_TITLES[i];
}

/**
 * Get a creative title for a mix by mix_number (fallback when no per-user index).
 * Uses mix_number so each mix gets a different title; stable per mix.
 */
export function getCreativeMixTitle(mixNumber: number): string {
  const index = (mixNumber - 1) % L;
  return CREATIVE_MIX_TITLES[index];
}
