/**
 * Global Daily Mix Generator
 * 
 * Generates daily mixes for non-authenticated users and users without listening history
 * Uses global trending data, top genres, and editorial curation
 */

import { supabase } from './supabase';
import { fetchWithCache, CACHE_KEYS, CACHE_TTL, configCache } from './configCache';

interface GlobalDailyMix {
  id: string;
  mix_number: number;
  title: string;
  description: string;
  genre_focus: string | null;
  mood_focus: string | null;
  cover_image_url: string | null;
  track_count: number;
  generated_at: string;
  artist_images?: string[];
  display_title?: string;
}

interface GlobalMixTrack {
  mix_id: string;
  song_id: string;
  position: number;
  explanation: string;
}

interface SongRow {
  id: string;
  title: string;
  artist_id: string | null;
  cover_image_url: string | null;
  duration_seconds: number | null;
  audio_url: string | null;
  play_count: number | null;
  created_at: string | null;
}

type SongGenreMap = Map<string, string[]>;

// Creative, curiosity-driven titles that make users want to tap
const CREATIVE_MIX_TITLES = [
  'Sounds You Slept On',
  'The Algorithm Broke Here',
  'What Your Friends Are Hiding',
  'Songs Before They Blow Up',
  'Underground Rising',
  'Next Up Worldwide',
  'The Late Night Drive Mix',
  'Vibes From Everywhere',
  'Breaking Out Right Now',
  'Hidden Heat',
  'Streets to Stadiums',
  'Uncharted Territory',
  'The Come Up Playlist',
  'Raw Talent Rising',
  'Future Classics Loading',
  'Global Sleeper Hits',
  'The Discovery Zone',
  'Underrated & Unstoppable',
  'From Bedrooms to Billboards',
  'The Wave Before It Breaks'
];

/**
 * Get or generate global daily mixes (cached for all users)
 */
export async function getGlobalDailyMixes(forceRefresh = false): Promise<GlobalDailyMix[]> {
  return fetchWithCache(
    CACHE_KEYS.GLOBAL_DAILY_MIXES,
    CACHE_TTL.ONE_HOUR * 4, // 4 hours cache
    async () => {
      // Try to get from database first
      const { data: existingMixes, error } = await supabase
        .from('global_daily_mix_playlists')
        .select('id, mix_number, title, description, genre_focus, mood_focus, cover_image_url, track_count, generated_at')
        .gt('expires_at', new Date().toISOString())
        // Keep UI stable: always return 1..4 for current active generation.
        .order('mix_number', { ascending: true })
        .limit(4);

      if (!error && existingMixes && existingMixes.length > 0) {
        return existingMixes;
      }

      // Do not auto-generate from the client. Global mixes should be generated by admin/cron.
      return [];
    },
    forceRefresh
  );
}

/**
 * Get tracks for a global mix
 */
export async function getGlobalMixTracks(mixId: string): Promise<any[]> {
  const { data: tracks, error } = await supabase
    .from('global_daily_mix_tracks')
    .select(`
      song_id,
      position,
      explanation,
      songs (
        id,
        title,
        artist_id,
        cover_image_url,
        duration_seconds,
        audio_url,
        play_count
      )
    `)
    .eq('mix_id', mixId)
    .order('position');

  if (error) throw error;
  return tracks || [];
}

/**
 * Generate new global mixes based on trending and popular content
 * 
 * Mix Strategy (4 playlists daily):
 * - 40% Global hits (what's hot worldwide)
 * - 30% Emerging artists (low exposure but rising play velocity)
 * - 20% Local-to-global crossovers (regional hits breaking out)
 * - 10% Wildcards (unexpected genres/moods)
 */
export async function generateGlobalMixes(): Promise<GlobalDailyMix[]> {
  // Prevent stale cards/IDs after regeneration.
  configCache.invalidate(CACHE_KEYS.GLOBAL_DAILY_MIXES);

  const config = await fetchWithCache(
    CACHE_KEYS.DAILY_MIX_CONFIG,
    CACHE_TTL.ONE_DAY,
    async () => {
      const { data } = await supabase
        .from('daily_mix_config')
        .select('*')
        .single();
      return data;
    }
  );

  const tracksPerMix = config?.tracks_per_mix || 25;
  const mixesCount = 4;
  const quota = getMixQuota(tracksPerMix);
  const nowIso = new Date().toISOString();
  const expiresIso = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();

  // Requirement: avoid duplicated generations; keep only a single active set.
  await supabase.from('global_daily_mix_playlists').delete();

  const mixes: GlobalDailyMix[] = [];

  // --- Mix 1: Global Hits (40% of total discovery) ---
  const globalHitsTracks = await getGlobalHitsTracks(quota.globalHits * mixesCount, tracksPerMix * mixesCount);
  
  // --- Mix 2: Emerging Artists (30% of total discovery) ---
  const emergingTracks = await getEmergingArtistsTracks(quota.emerging * mixesCount, tracksPerMix * mixesCount);
  
  // --- Mix 3: Local-to-Global Crossovers (20% of total discovery) ---
  const crossoverTracks = await getLocalToGlobalTracks(quota.crossover * mixesCount, tracksPerMix * mixesCount);
  
  // --- Mix 4: Wildcards (10% of total discovery) ---
  const wildcardTracks = await getWildcardTracks(quota.wildcard * mixesCount, tracksPerMix * mixesCount);

  const globalHits = dedupeSongsById(globalHitsTracks);
  const emerging = dedupeSongsById(emergingTracks);
  const crossovers = dedupeSongsById(crossoverTracks);
  const wildcards = dedupeSongsById(wildcardTracks);
  const allCandidateSongs = dedupeSongsById([...globalHits, ...emerging, ...crossovers, ...wildcards]);
  const songGenres = await getSongGenres(allCandidateSongs.map((song) => song.id));
  const maxPerGenre = Math.max(3, Math.ceil(tracksPerMix * 0.35));
  const maxPerArtist = Math.max(1, Math.floor(tracksPerMix * 0.2));

  // Build 4 balanced mixes with strict 40/30/20/10 quotas.
  const mixDefinitions = [
    { description: 'Global hits, rising stars, and unexpected finds curated for discovery' },
    { description: 'Underground artists breaking through with tracks you have not heard yet' },
    { description: 'Regional sounds crossing borders and climbing global charts' },
    { description: 'Unexpected genres, wildcards, and the next wave of global music' }
  ];

  let globalCursor = 0;
  let emergingCursor = 0;
  let crossoverCursor = 0;
  let wildcardCursor = 0;
  const usedSongIds = new Set<string>();

  for (let i = 0; i < mixDefinitions.length; i++) {
    const def = mixDefinitions[i];
    const songs: SongRow[] = [];
    const mixGenreCounts = new Map<string, number>();
    const mixArtistCounts = new Map<string, number>();

    globalCursor = pushFromPool(songs, globalHits, globalCursor, quota.globalHits, usedSongIds, songGenres, mixGenreCounts, maxPerGenre, mixArtistCounts, maxPerArtist);
    emergingCursor = pushFromPool(songs, emerging, emergingCursor, quota.emerging, usedSongIds, songGenres, mixGenreCounts, maxPerGenre, mixArtistCounts, maxPerArtist);
    crossoverCursor = pushFromPool(songs, crossovers, crossoverCursor, quota.crossover, usedSongIds, songGenres, mixGenreCounts, maxPerGenre, mixArtistCounts, maxPerArtist);
    wildcardCursor = pushFromPool(songs, wildcards, wildcardCursor, quota.wildcard, usedSongIds, songGenres, mixGenreCounts, maxPerGenre, mixArtistCounts, maxPerArtist);

    fillFromFallbackPools(
      songs,
      tracksPerMix,
      [globalHits, emerging, crossovers, wildcards],
      usedSongIds,
      songGenres,
      mixGenreCounts,
      maxPerGenre,
      mixArtistCounts,
      maxPerArtist
    );

    // Guarantee artist diversity for card collage and user perception.
    ensureMinimumDistinctArtists(songs, [globalHits, emerging, crossovers, wildcards], 3, usedSongIds);
    
    if (songs.length === 0) continue;

    const mixTitle = getRotatingTitle(i, nowIso);

    const { data: playlist, error: playlistError } = await supabase
      .from('global_daily_mix_playlists')
      .insert({
        mix_number: i + 1,
        title: mixTitle,
        description: def.description,
        genre_focus: null,
        mood_focus: null,
        cover_image_url: songs[0]?.cover_image_url || null,
        track_count: songs.length,
        generated_at: nowIso,
        expires_at: expiresIso
      })
      .select()
      .single();

    if (playlistError || !playlist) continue;

    const tracksToInsert: GlobalMixTrack[] = songs.map((song, idx) => ({
      mix_id: playlist.id,
      song_id: song.id,
      position: idx + 1,
      explanation: getTrackExplanation(song, idx, tracksPerMix)
    }));

    await supabase.from('global_daily_mix_tracks').insert(tracksToInsert);
    mixes.push(playlist);
  }

  // Ensure subsequent reads get fresh titles and IDs.
  configCache.invalidate(CACHE_KEYS.GLOBAL_DAILY_MIXES);
  return mixes;
}

/**
 * Get global hits: high play_count, recent activity
 */
async function getGlobalHitsTracks(target: number, buffer: number): Promise<any[]> {
  const { data } = await supabase
    .from('songs')
    .select('id, title, artist_id, cover_image_url, duration_seconds, audio_url, play_count, created_at')
    .gte('created_at', new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString()) // last 60 days
    .order('play_count', { ascending: false })
    .limit(Math.max(target + buffer, buffer));
  
  return data || [];
}

/**
 * Get emerging artists: newer songs (< 30 days), low-to-mid play count but rising
 */
async function getEmergingArtistsTracks(target: number, buffer: number): Promise<any[]> {
  const { data } = await supabase
    .from('songs')
    .select('id, title, artist_id, cover_image_url, duration_seconds, audio_url, play_count, created_at')
    .gte('created_at', new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()) // last 30 days
    .lt('play_count', 5000) // not yet mainstream
    .gt('play_count', 100)   // has momentum
    .order('created_at', { ascending: false })
    .limit(Math.max(target + buffer, buffer));
  
  return data || [];
}

/**
 * Get local-to-global crossovers: songs with regional traction breaking into global
 * (Proxy: songs with sudden play_count velocity in recent window)
 */
async function getLocalToGlobalTracks(target: number, buffer: number): Promise<any[]> {
  const { data } = await supabase
    .from('songs')
    .select('id, title, artist_id, cover_image_url, duration_seconds, audio_url, play_count, created_at')
    .gte('created_at', new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString()) // 45 days window
    .gt('play_count', 500)
    .lt('play_count', 15000)
    .order('play_count', { ascending: false })
    .limit(Math.max(target + buffer, buffer));
  
  return data || [];
}

/**
 * Get wildcards: random genre/mood picks, older hidden gems
 */
async function getWildcardTracks(target: number, buffer: number): Promise<any[]> {
  const { data } = await supabase
    .from('songs')
    .select('id, title, artist_id, cover_image_url, duration_seconds, audio_url, play_count, created_at')
    .gt('play_count', 50)
    .order('created_at', { ascending: false })
    .limit(Math.max(target + buffer, buffer));
  
  // Shuffle for wildcard randomness
  return (data || []).sort(() => Math.random() - 0.5);
}

/**
 * Generate contextual explanation for each track
 */
function getTrackExplanation(song: SongRow, position: number, totalTracks: number): string {
  const playCount = song.play_count || 0;
  const age = song.created_at ? Date.now() - new Date(song.created_at).getTime() : Number.POSITIVE_INFINITY;
  const daysOld = Math.floor(age / (1000 * 60 * 60 * 24));

  if (playCount > 10000) {
    return 'Trending globally right now';
  } else if (playCount > 2000 && daysOld < 30) {
    return 'Emerging artist on the rise';
  } else if (daysOld < 14) {
    return 'Fresh release breaking through';
  } else if (position > totalTracks * 0.7) {
    return 'Wildcard pick for you';
  } else {
    return 'Hidden gem worth discovering';
  }
}

function getMixQuota(tracksPerMix: number): { globalHits: number; emerging: number; crossover: number; wildcard: number } {
  const globalHits = Math.round(tracksPerMix * 0.4);
  const emerging = Math.round(tracksPerMix * 0.3);
  const crossover = Math.round(tracksPerMix * 0.2);
  const wildcard = Math.max(tracksPerMix - globalHits - emerging - crossover, 0);
  return { globalHits, emerging, crossover, wildcard };
}

async function getSongGenres(songIds: string[]): Promise<SongGenreMap> {
  const genreMap: SongGenreMap = new Map();
  if (!songIds.length) return genreMap;

  const { data } = await supabase
    .from('song_genres')
    .select(`
      song_id,
      genres (
        name
      )
    `)
    .in('song_id', songIds);

  (data || []).forEach((row: any) => {
    const genreName = row?.genres?.name;
    if (!genreName || !row?.song_id) return;
    const existing = genreMap.get(row.song_id) || [];
    existing.push(String(genreName).trim().toLowerCase());
    genreMap.set(row.song_id, existing);
  });

  return genreMap;
}

function getPrimaryGenre(song: SongRow, songGenres: SongGenreMap): string {
  const genres = songGenres.get(song.id) || [];
  return genres[0] || '__unknown__';
}

function getArtistKey(song: SongRow): string {
  return song.artist_id || '__unknown_artist__';
}

function dedupeSongsById(songs: SongRow[]): SongRow[] {
  const seen = new Set<string>();
  return songs.filter((song) => {
    if (!song?.id || seen.has(song.id)) return false;
    seen.add(song.id);
    return true;
  });
}

function pushFromPool(
  target: SongRow[],
  pool: SongRow[],
  cursor: number,
  take: number,
  usedSongIds: Set<string>,
  songGenres: SongGenreMap,
  mixGenreCounts: Map<string, number>,
  maxPerGenre: number,
  mixArtistCounts: Map<string, number>,
  maxPerArtist: number
): number {
  let picked = 0;
  let nextCursor = cursor;

  while (nextCursor < pool.length && picked < take) {
    const candidate = pool[nextCursor];
    nextCursor += 1;
    if (!candidate?.id || usedSongIds.has(candidate.id)) continue;
    const genre = getPrimaryGenre(candidate, songGenres);
    const currentGenreCount = mixGenreCounts.get(genre) || 0;
    if (currentGenreCount >= maxPerGenre) continue;
    const artistKey = getArtistKey(candidate);
    const currentArtistCount = mixArtistCounts.get(artistKey) || 0;
    if (currentArtistCount >= maxPerArtist) continue;
    target.push(candidate);
    usedSongIds.add(candidate.id);
    mixGenreCounts.set(genre, currentGenreCount + 1);
    mixArtistCounts.set(artistKey, currentArtistCount + 1);
    picked += 1;
  }

  return nextCursor;
}

function fillFromFallbackPools(
  target: SongRow[],
  desiredCount: number,
  pools: SongRow[][],
  usedSongIds: Set<string>,
  songGenres: SongGenreMap,
  mixGenreCounts: Map<string, number>,
  maxPerGenre: number,
  mixArtistCounts: Map<string, number>,
  maxPerArtist: number
): void {
  if (target.length >= desiredCount) return;

  // First pass: enforce diversity.
  for (const pool of pools) {
    for (const song of pool) {
      if (target.length >= desiredCount) return;
      if (!song?.id || usedSongIds.has(song.id)) continue;
      const genre = getPrimaryGenre(song, songGenres);
      const currentGenreCount = mixGenreCounts.get(genre) || 0;
      if (currentGenreCount >= maxPerGenre) continue;
      const artistKey = getArtistKey(song);
      const currentArtistCount = mixArtistCounts.get(artistKey) || 0;
      if (currentArtistCount >= maxPerArtist) continue;
      target.push(song);
      usedSongIds.add(song.id);
      mixGenreCounts.set(genre, currentGenreCount + 1);
      mixArtistCounts.set(artistKey, currentArtistCount + 1);
    }
  }

  // Second pass: relax cap only when needed to fill to target size.
  if (target.length >= desiredCount) return;
  for (const pool of pools) {
    for (const song of pool) {
      if (target.length >= desiredCount) return;
      if (!song?.id || usedSongIds.has(song.id)) continue;
      const genre = getPrimaryGenre(song, songGenres);
      const artistKey = getArtistKey(song);
      target.push(song);
      usedSongIds.add(song.id);
      mixGenreCounts.set(genre, (mixGenreCounts.get(genre) || 0) + 1);
      mixArtistCounts.set(artistKey, (mixArtistCounts.get(artistKey) || 0) + 1);
    }
  }
}

function getRotatingTitle(mixIndex: number, nowIso: string): string {
  const daySeed = new Date(nowIso).getDate();
  const start = (daySeed * 4) % CREATIVE_MIX_TITLES.length;
  return CREATIVE_MIX_TITLES[(start + mixIndex) % CREATIVE_MIX_TITLES.length];
}

function ensureMinimumDistinctArtists(
  songs: SongRow[],
  pools: SongRow[][],
  minDistinctArtists: number,
  usedSongIds: Set<string>
): void {
  const artistSet = new Set<string>(songs.map((song) => getArtistKey(song)));
  if (artistSet.size >= minDistinctArtists) return;

  const byArtist = new Map<string, SongRow[]>();
  for (const pool of pools) {
    for (const song of pool) {
      if (!song?.id || usedSongIds.has(song.id)) continue;
      const artistKey = getArtistKey(song);
      const list = byArtist.get(artistKey) || [];
      list.push(song);
      byArtist.set(artistKey, list);
    }
  }

  const currentArtists = new Set<string>(songs.map((song) => getArtistKey(song)));
  const candidateArtists = Array.from(byArtist.keys()).filter((artist) => !currentArtists.has(artist));
  if (!candidateArtists.length) return;

  for (const candidateArtist of candidateArtists) {
    if (new Set<string>(songs.map((song) => getArtistKey(song))).size >= minDistinctArtists) break;
    const replacement = byArtist.get(candidateArtist)?.[0];
    if (!replacement) continue;

    // Replace from the end to minimize impact on primary ranking at top positions.
    const replaceIndex = songs.length - 1;
    if (replaceIndex < 0) break;

    const removed = songs[replaceIndex];
    songs[replaceIndex] = replacement;
    usedSongIds.add(replacement.id);
    // Keep removed song ID available for future mixes only if it was unique to this mix.
    if (removed?.id) {
      usedSongIds.delete(removed.id);
    }
  }
}

/**
 * Check if global mixes need refresh (run from admin or cron)
 */
export async function refreshGlobalMixesIfNeeded(): Promise<boolean> {
  const { data: existing } = await supabase
    .from('global_daily_mix_playlists')
    .select('id')
    .gt('expires_at', new Date().toISOString())
    .limit(1);

  if (!existing || existing.length === 0) {
    await generateGlobalMixes();
    return true;
  }

  return false;
}
